var keyMirror = require('keymirror');

module.exports = keyMirror({
  REQUESTS_PENDING_ON_OTHERS: 'REQUESTS_PENDING_ON_OTHERS',
  REQUESTS_PENDING_ON_ME: 'REQUESTS_PENDING_ON_ME',
  REQUESTS_COMPLETED: 'REQUESTS_COMPLETED',

});
