var keyMirror = require('keymirror');

module.exports = keyMirror({
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',
  USER_REGISTER_LOADING: 'USER_REGISTER_LOADING',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  USER_LOGIN_LOADING: 'USER_LOGIN_LOADING'
});
